creating numpy array
1.np.array() // 1-D & 2-D
2.np.zeroes/ones/empty/random()
3.np.arange()
4.np.linspace()
5.copy()
6.identity()


In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
#creating missing arrary
arr=np.array([1,23,4,45,np.nan,6,7,76])
arr

array([ 1., 23.,  4., 45., nan,  6.,  7., 76.])

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr6=np.arange(5,16,3)
arr6

array([ 5,  8, 11, 14])

In [10]:
arr7=np.linspace(1,9,3)     #1 se lekr 9 tak equidistant point 3 ya 4
arr7

array([1., 5., 9.])

In [11]:
arr8=arr7.copy()
arr8

array([1., 5., 9.])