broadcasting
--it means performing arthimetic operations on dissimilar array


In [1]:
import numpy as np

In [2]:
a=np.arange(8).reshape(2,4)
b=np.arange(8,16).reshape(2,4)

In [3]:
a+b

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
a=np.arange(3).reshape(1,3)
b=np.arange(12).reshape(4,3)
#agr 1 hai to koi ek same hona chaiye row ya col

print(a)
print("  ")
print(b)

[[0 1 2]]
  
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
a+b

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])