random
seed
uniform
reshape
randint
max
condition[(),()]
where
sort
percentile
append
concatinate
unique
expand
argmax ,max
cumsum,cumprod
histogram
corelation - 0 no relation
             1 fully depend  x increse y increase vice
             -1 inversex and y relation
            
isin
flip 
put
delete




In [1]:
import numpy as np
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
b
a

array([83, 32, 15, 94,  3, 11, 50, 56, 21, 17, 21, 32, 55, 75, 75])

In [2]:
b=np.where(a%2==1,-6,a)
b

array([-6, 32, -6, 94, -6, -6, 50, 56, -6, -6, -6, 32, -6, -6, -6])

In [3]:
a=np.sort(a)
a

array([ 3, 11, 15, 17, 21, 21, 32, 32, 50, 55, 56, 75, 75, 83, 94])

In [4]:
np.percentile(a,30)

21.0

In [5]:
np.sort(a)

array([ 3, 11, 15, 17, 21, 21, 32, 32, 50, 55, 56, 75, 75, 83, 94])

In [6]:
np.sort(b)  #row wise sort 

array([-6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 32, 32, 50, 56, 94])

In [7]:
np.sort(b,axis=0) #col wise sort axis=0 row=1

array([-6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 32, 32, 50, 56, 94])

In [8]:
np.append(a,200) #add one item in 1d
np.append(b,np.random.random((b.shape[0],1)),axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
c=np.arange(0,24).reshape(4,6)
d=np.arange(12,36).reshape(4,6)
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17, 24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23, 30, 31, 32, 33, 34, 35]])

In [ ]:
a

array([30,  9, 50, 96, 35, 24, 78, 84, 16, 60, 16, 26, 85, 22, 27])

In [ ]:
e=np.array([11,11,1,1,1,12,3,9,3,4,5,5])

In [ ]:
np.unique(e)

array([ 1,  3,  4,  5,  9, 11, 12])

In [ ]:
a # expand 1d to 2d ,, 2d to 3d

array([30,  9, 50, 96, 35, 24, 78, 84, 16, 60, 16, 26, 85, 22, 27])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=0)

array([[30,  9, 50, 96, 35, 24, 78, 84, 16, 60, 16, 26, 85, 22, 27]])

In [ ]:
#np.where(condition,true,false)
np.where(a>30,"raja",a)

array(['30', '9', 'raja', 'raja', 'raja', '24', 'raja', 'raja', '16',
       'raja', '16', '26', 'raja', '22', '27'], dtype='<U11')

In [ ]:
np.where(a%2==0,0,a)

array([ 0,  9,  0,  0, 35,  0,  0,  0,  0,  0,  0,  0, 85,  0, 27])

In [ ]:
np.max(a)     #give max element
np.argmax(a)  #give index of max element

96

In [ ]:
a

array([30,  9, 50, 96, 35, 24, 78, 84, 16, 60, 16, 26, 85, 22, 27])

In [ ]:
np.cumsum(a)

array([ 30,  39,  89, 185, 220, 244, 322, 406, 422, 482, 498, 524, 609,
       631, 658])

In [ ]:
b

array([[59, 19, 33, 71],
       [47, 44,  6, 47],
       [ 8, 13, 42, 45],
       [61, 39, 12, 84],
       [68, 74, 10, 25],
       [92, 93, 90,  1]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 59,  78, 111, 182],
       [ 47,  91,  97, 144],
       [  8,  21,  63, 108],
       [ 61, 100, 112, 196],
       [ 68, 142, 152, 177],
       [ 92, 185, 275, 276]])

In [ ]:
a

array([30,  9, 50, 96, 35, 24, 78, 84, 16, 60, 16, 26, 85, 22, 27])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,100])  #no.of item in bins gap

(array([2, 1, 2, 1, 2, 7], dtype=int64),
 array([  0,  10,  20,  30,  40,  50, 100]))

In [ ]:
salary=np.array([200,400,250,350,600])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [ ]:
a
items=np.random.randint(1,20,7)
items
np.isin(a,items)



array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
a

array([ 3,  7, 14, 26, 27, 33, 45, 49, 59, 63, 70, 72, 79, 83, 96])

In [ ]:
np.flip(a)

array([96, 83, 79, 72, 70, 63, 59, 49, 45, 33, 27, 26, 14,  7,  3])

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
np.flip(c,axis=0)

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [ ]:
a


array([ 3,  7, 14, 26, 27, 33, 45, 49, 59, 63, 70, 72, 79, 83, 96])

In [ ]:
np.put(a,[0,1],[110,50])
a

array([110,  50,  14,  26,  27,  33,  45,  49,  59,  63,  70,  72,  79,
        83,  96])

In [ ]:
#np.delete(a,index)
np.delete(a,[0,1,2])

array([26, 27, 33, 45, 49, 59, 63, 70, 72, 79, 83, 96])

In [ ]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [ ]:
np.union1d(m,n)
np.intersect1d(m,n)
np.setdiff1d(m,n)
np.setxor1d(m,n)
np.in1d(m,5)
#m[np.in1d(m,5)]

array([False, False, False, False,  True])

In [ ]:
a

array([110,  50,  14,  26,  27,  33,  45,  49,  59,  63,  70,  72,  79,
        83,  96])

In [ ]:
np.clip(a,a_max=75,a_min=25)

array([75, 50, 25, 26, 27, 33, 45, 49, 59, 63, 70, 72, 75, 75, 75])

In [ ]:
o=np.arange(100)
o

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#sigmoid
def sigmoid(array):
    return 1/(1+np.exp(-(array)))

u=np.arange(100)

sigmoid(u)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661,
       0.9999546 , 0.9999833 , 0.99999386, 0.99999774, 0.99999917,
       0.99999969, 0.99999989, 0.99999996, 0.99999998, 0.99999999,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [ ]:
#mean squared error
j=np.random.randint(1,20,7)
p=np.random.randint(1,20,7)

In [ ]:
def mse(actual,predicted):
    return np.mean((actual-predicted)**2)

mse(j,p)

42.0

In [ ]:
#missing values
l=np.array([1,23,4,45,np.nan,6,7,76])
l

array([ 1., 23.,  4., 45., nan,  6.,  7., 76.])

In [ ]:
#finding nan value using isnan
np.isnan(l)

array([False, False, False, False,  True, False, False, False])

In [ ]:
#printing only nan 
l[np.isnan(l)]

array([nan])

In [ ]:
#now reverse using ~ to get not nan value
#this code remove nan value from data
l[~np.isnan(l)]

array([ 1., 23.,  4., 45.,  6.,  7., 76.])