Properties & Attribute
1.shape
2.nDim
3.Size
4.Itemsize
5.Dtype
6.astype()

In [1]:
import numpy as np

In [2]:
arr1=np.array([[[1,2],[3,4],[5,6]]])
arr1

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [3]:
arr1.shape

(1, 3, 2)

In [4]:
arr2=np.array([1,2,3,4,5,6,7,8])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr2.shape

(8,)

In [6]:
arr3=np.array([[1,2],[3,4]])
arr3

array([[1, 2],
       [3, 4]])

In [7]:
arr3.shape

(2, 2)

In [8]:
arr1.ndim

3

In [9]:
arr2.ndim

1

In [10]:
arr3.ndim

2

In [11]:
arr4=np.linspace(5,15,3)
arr4

array([ 5., 10., 15.])

size= no of items
itemsize= no.of bits item has. int=4 float=8

In [12]:
arr1.size

6

In [13]:
arr3.size 

4

In [14]:
arr3.itemsize

4

In [15]:
arr4.itemsize

8

In [16]:
arr4.dtype

dtype('float64')

In [17]:
arr3.dtype

dtype('int32')

  astype() --convert int to float in array

In [28]:
arr3.astype('float')

array([[1., 2.],
       [3., 4.]])

In [29]:
arr3.dtype

dtype('int32')

In [30]:
arr3.size

4