In [1]:
import numpy as np
arr1=np.arange(24).reshape(6,4)
arr1 
#print 3rd col

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
# arr1[x:y,x:y]
arr1[4:5,2:4]

array([[18, 19]])

In [3]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [5]:
arr1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [6]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [7]:
#iteration -- np.nditer(array_)

In [8]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [9]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
