1.basic operations
a. A-B
b. B*2
c. A<35
d. A*B(Element-wise multiply )
e. A.DOT(B)
f. a*=b

In [1]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [3]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [4]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [5]:
arr1*3

array([ 3,  6,  9, 12, 15, 18])

In [6]:
arr1>3

array([False, False, False,  True,  True,  True])

In [7]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

#performing dot product 2*3 -- 3*2 == 2*2  (3==3)


In [8]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

2.BINARY OPERATION
a. a.min() // a.max()
b. a.sum(axis=0/1) 
 axis=0 (col wise batao sab column ka)
 axis=1 ( row wise)

In [9]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [10]:
arr4.max()

11

In [11]:
arr4.min()

6

In [12]:
arr4.min(axis=0)

array([6, 7])

In [13]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [14]:
arr4.sum(axis=1)

array([13, 17, 21])

In [15]:
arr4.mean()

8.5

In [16]:
arr4.std()  #STANDARD DEVIATION

1.707825127659933

3,Universal functions
a. np.exp(arr1)
b. np.sqrt()
c. np.median()
d. np.sin()

In [17]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [18]:
np.median(arr4)

8.5

In [19]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])