1. ravel -- convrt higher dim to 1d
2. reshape -- factors
3. transpose -- row->col & col->row
4. stacking -- combine 2 array
            a. np.hstack(aar1,arr2) -- horizontal add
            b. np.vstack(arr1,arr2) -- vertival combine
5. splitting  -- split 1 array in equal parts
            a. np.split(arr1,3) -- 3 is no.of division

In [1]:
import numpy as np

In [2]:
arr1=np.arange(24).reshape(6,4)

In [3]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
arr1.ndim

2

In [5]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
arr1.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [7]:
arr2=np.arange(12,36).reshape(6,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [8]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23],
       [12, 13, 14, 15, 24, 25, 26, 27],
       [16, 17, 18, 19, 28, 29, 30, 31],
       [20, 21, 22, 23, 32, 33, 34, 35]])

In [9]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [10]:
np.hsplit(arr1,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]