In [1]:
import numpy as np
arr1=np.random.randint(low=1, high=100 , size=20).reshape(4,5)
arr1

array([[93, 21, 64, 30, 56],
       [83, 97, 75, 36, 48],
       [68,  3,  3,  6, 51],
       [70, 82, 87,  8, 50]])

In [2]:
arr1>50

array([[ True, False,  True, False,  True],
       [ True,  True,  True, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False]])

In [5]:
arr1[arr1>50]  #this is indexing boolean array , we overlap

array([93, 64, 56, 83, 97, 75, 68, 51, 70, 82, 87])

In [6]:
#multi condition
arr1[(arr1>50) & (arr1%2!=0)]

array([93, 83, 97, 75, 51, 87])

In [7]:
arr1[(arr1>50) & (arr1%2!=0)]=0
arr1

array([[ 0, 21, 64, 30, 56],
       [ 0,  0,  0, 36, 48],
       [68,  3,  3,  6,  0],
       [70, 82,  0,  8, 50]])